### ISSUE TITLE
Can't stop

### ISSUE THREAD

**Issue by Ai00000** [JohannesDeml/EditorAudioUtils#4]
Using StopAll when playing multiple sound effects still does not stop

**Comment by JohannesDeml** [comment]
Hey there,

thanks for the report, but I need more information from you to reproduce the problem. Please provide the following:
* unity version
* EditorAudioUtils version
* Information about the audio file (format, length) or if possible attach the file or send it to public@deml.io

**Comment by JohannesDeml** [comment]
Haven't received any further information, closing it for now. If you still encounter this problem, please post here, and we'll reopen it.
